### ISSUE TITLE
The initial directory structure is not correct.

### ISSUE THREAD

**Issue by qjones3** [drupalninja/drupalx-project#9]
The following commands were run:

1. `composer create-project drupalninja/drupalx-project:10.x-dev my-custom-project --no-interaction`
2. `ddev config`
3. `ddev install`
4. `ddev . drush cex -y`
5. `ddev . drush si -y drupalx --existing-config`

<img width="746" alt="Screenshot 2024-07-18 at 1 48 14 PM" src="https://github.com/user-attachments/assets/27a8c96b-ec16-4b1f-a858-49d984bdc106">

**Comment by nextagencyio** [comment]
Thanks I will take a look

**Comment by nextagencyio** [comment]
Fixed some paths in https://github.com/drupalninja/drupalx_theme/commit/eb1847dacc8bcd3b604756da61e13bcdea60f149

Updated the lock on this project so you can test again
